name: Playwright Tests
on:
  push:
    branches: [master, develop]
  pull_request:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
    strategy:
      matrix:
        package: ["apps/web"]
    steps:
      - uses: actions/checkout@v4
        name: "ğŸ›ï¸ Checkout repository"
        with:
          fetch-depth: 1

      - name: "ğŸ“¦ Install pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 10.12.2
          run_install: false

      - name: "ğŸ—‚ï¸ Use Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: "ğŸ“¥ Install dependencies"
        run: pnpm install --frozen-lockfile

      - name: "ğŸ­ Cache Playwright browsers"
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: "ğŸ’» Install Playwright Browsers"
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm --filter ${{ matrix.package }} exec playwright install --with-deps chromium

      - name: "ğŸ§ª Run Playwright tests"
        run: pnpm --filter ${{ matrix.package }} test

      - uses: actions/upload-artifact@v4
        name: "ğŸ“¤ Upload Playwright report"
        if: always() && !cancelled()
        with:
          name: playwright-report
          path: ${{ matrix.package }}/playwright-report/
          retention-days: 7
